apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://10.43.235.109:8200" # Pegue o IP do servidor através do comando `kubectl get svc`
      path: "secret"
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "internal-app"
          serviceAccountRef:
            name: "k8s-service-acct"
