apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: k3s-default
  namespace: sno01
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: k3s-default
  data:
  - secretKey: foobar
    remoteRef:
      key: secret/foo
      property: my-value
